version: '3'

services:

  db:
    build:
      context: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

  nodeserver:
    build:
      context: node
    container_name: nodeserver
    entrypoint: ./.docker/entrypoint.sh
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - node_network
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - node_network
    depends_on:
      - nodeserver

networks:
  node_network:
    driver: bridge